<template>
  <div class="mt-10" v-if="data.records.length > 0">
    <div class="title section_title">Rejection Reasons</div>
    <s-grid
      v-model="data.records"
      class="w-full se-grid grid-line-items"
      ref="listControl"
      hide-select
      hide-search
      hide-sort
      hide-refresh-button
      hide-new-button
      hide-detail
      hide-delete-button
      hide-control
      hide-action
      hide-paging
      :config="data.gridCfg"
    >
      <template #item_UserID="{ item }">
        <s-input
          v-model="item.UserID"
          class="w-full"
          read-only
          use-list
          :lookup-url="`/tenant/employee/find`"
          lookup-key="_id"
          :lookup-labels="['Name']"
          :lookup-searchs="['_id', 'Name']"
        ></s-input>
      </template>
    </s-grid>
  </div>
</template>

<script setup>
import { reactive, ref, onMounted, inject } from "vue";
import { SGrid, SInput } from "suimjs";

const axios = inject("axios");
const listControl = ref(null);

const props = defineProps({
  journalType: { type: String, default: "" },
  journalID: { type: String, default: "" },
  journalID: { type: String, default: "" },
  readUrl: {
    type: String,
    default: "/scm/new/postingprofile/get-approval-by-source",
  },
});
const data = reactive({
  gridCfg: {},
  records: [],
});

onMounted(() => {
  const fields = [
    {
      field: "Line",
      kind: "number",
      label: "Line",
      halign: "start",
      valign: "start",
      labelField: "",
      length: 0,
      width: "",
      pos: 1000,
      readType: "show",
      decimal: 0,
      dateFormat: "DD-MMM-YYYY hh:mm:ss Z",
      unit: "",
      input: {
        field: "Line",
        label: "Line",
        hint: "",
        hide: false,
        placeHolder: "Line",
        kind: "number",
        disable: false,
        required: false,
        multiple: false,
        multiRow: 1,
        minLength: 0,
        maxLength: 999,
        readOnly: false,
        readOnlyOnEdit: false,
        readOnlyOnNew: false,
        useList: false,
        allowAdd: false,
        items: [],
        useLookup: false,
        lookupUrl: "",
        lookupKey: "",
        lookupLabels: null,
        lookupSearchs: null,
        lookupFormat1: "",
        lookupFormat2: "",
        showTitle: false,
        showHint: false,
        showDetail: false,
        fixTitle: false,
        fixDetail: false,
        section: "General",
        sectionWidth: "",
        row: 0,
        col: 0,
        labelField: "",
        decimal: 0,
        dateFormat: "DD-MMM-YYYY hh:mm:ss Z",
        unit: "",
        width: "",
        spaceBefore: 0,
        spaceAfter: 0,
      },
    },
    {
      field: "UserID",
      kind: "text",
      label: "User ID",
      halign: "start",
      valign: "start",
      labelField: "",
      length: 0,
      width: "",
      pos: 1000,
      readType: "show",
      decimal: 0,
      dateFormat: "DD-MMM-YYYY hh:mm:ss Z",
      unit: "",
      input: {
        field: "UserID",
        label: "User ID",
        hint: "",
        hide: false,
        placeHolder: "User ID",
        kind: "text",
        disable: false,
        required: false,
        multiple: false,
        multiRow: 1,
        minLength: 0,
        maxLength: 999,
        readOnly: false,
        readOnlyOnEdit: false,
        readOnlyOnNew: false,
        useList: false,
        allowAdd: false,
        items: [],
        useLookup: false,
        lookupUrl: "",
        lookupKey: "",
        lookupLabels: null,
        lookupSearchs: null,
        lookupFormat1: "",
        lookupFormat2: "",
        showTitle: false,
        showHint: false,
        showDetail: false,
        fixTitle: false,
        fixDetail: false,
        section: "General",
        sectionWidth: "",
        row: 0,
        col: 0,
        labelField: "",
        decimal: 0,
        dateFormat: "DD-MMM-YYYY hh:mm:ss Z",
        unit: "",
        width: "",
        spaceBefore: 0,
        spaceAfter: 0,
      },
    },
    {
      field: "Status",
      kind: "text",
      label: "Status",
      halign: "start",
      valign: "start",
      labelField: "",
      length: 0,
      width: "",
      pos: 1000,
      readType: "show",
      decimal: 0,
      dateFormat: "DD-MMM-YYYY hh:mm:ss Z",
      unit: "",
      input: {
        field: "Status",
        label: "Status",
        hint: "",
        hide: false,
        placeHolder: "Status",
        kind: "text",
        disable: false,
        required: false,
        multiple: false,
        multiRow: 1,
        minLength: 0,
        maxLength: 999,
        readOnly: false,
        readOnlyOnEdit: false,
        readOnlyOnNew: false,
        useList: false,
        allowAdd: false,
        items: [],
        useLookup: false,
        lookupUrl: "",
        lookupKey: "",
        lookupLabels: null,
        lookupSearchs: null,
        lookupFormat1: "",
        lookupFormat2: "",
        showTitle: false,
        showHint: false,
        showDetail: false,
        fixTitle: false,
        fixDetail: false,
        section: "General",
        sectionWidth: "",
        row: 0,
        col: 0,
        labelField: "",
        decimal: 0,
        dateFormat: "DD-MMM-YYYY hh:mm:ss Z",
        unit: "",
        width: "",
        spaceBefore: 0,
        spaceAfter: 0,
      },
    },
    {
      field: "Text",
      kind: "text",
      label: "Reason",
      halign: "start",
      valign: "start",
      labelField: "",
      length: 0,
      width: "",
      pos: 1000,
      readType: "show",
      decimal: 0,
      dateFormat: "DD-MMM-YYYY hh:mm:ss Z",
      unit: "",
      input: {
        field: "Text",
        label: "Reason",
        hint: "",
        hide: false,
        placeHolder: "Text",
        kind: "text",
        disable: false,
        required: false,
        multiple: false,
        multiRow: 1,
        minLength: 0,
        maxLength: 999,
        readOnly: false,
        readOnlyOnEdit: false,
        readOnlyOnNew: false,
        useList: false,
        allowAdd: false,
        items: [],
        useLookup: false,
        lookupUrl: "",
        lookupKey: "",
        lookupLabels: null,
        lookupSearchs: null,
        lookupFormat1: "",
        lookupFormat2: "",
        showTitle: false,
        showHint: false,
        showDetail: false,
        fixTitle: false,
        fixDetail: false,
        section: "General",
        sectionWidth: "",
        row: 0,
        col: 0,
        labelField: "",
        decimal: 0,
        dateFormat: "DD-MMM-YYYY hh:mm:ss Z",
        unit: "",
        width: "",
        spaceBefore: 0,
        spaceAfter: 0,
      },
    },
    {
      field: "Assigned",
      kind: "datetime",
      label: "Assigned",
      halign: "start",
      valign: "start",
      labelField: "",
      length: 0,
      width: "",
      pos: 1000,
      readType: "show",
      decimal: 0,
      dateFormat: "DD-MMM-YYYY hh:mm:ss Z",
      unit: "",
      input: {
        field: "Assigned",
        label: "Assigned",
        hint: "",
        hide: false,
        placeHolder: "Assigned",
        kind: "datetime",
        disable: false,
        required: false,
        multiple: false,
        multiRow: 1,
        minLength: 0,
        maxLength: 999,
        readOnly: false,
        readOnlyOnEdit: false,
        readOnlyOnNew: false,
        useList: false,
        allowAdd: false,
        items: [],
        useLookup: false,
        lookupUrl: "",
        lookupKey: "",
        lookupLabels: null,
        lookupSearchs: null,
        lookupFormat1: "",
        lookupFormat2: "",
        showTitle: false,
        showHint: false,
        showDetail: false,
        fixTitle: false,
        fixDetail: false,
        section: "General",
        sectionWidth: "",
        row: 0,
        col: 0,
        labelField: "",
        decimal: 0,
        dateFormat: "DD-MMM-YYYY hh:mm:ss Z",
        unit: "",
        width: "",
        spaceBefore: 0,
        spaceAfter: 0,
      },
    },
    {
      field: "Confirmed",
      kind: "datetime",
      label: "Confirmed",
      halign: "start",
      valign: "start",
      labelField: "",
      length: 0,
      width: "",
      pos: 1000,
      readType: "show",
      decimal: 0,
      dateFormat: "DD-MMM-YYYY hh:mm:ss Z",
      unit: "",
      input: {
        field: "Confirmed",
        label: "Confirmed",
        hint: "",
        hide: false,
        placeHolder: "Confirmed",
        kind: "datetime",
        disable: false,
        required: false,
        multiple: false,
        multiRow: 1,
        minLength: 0,
        maxLength: 999,
        readOnly: false,
        readOnlyOnEdit: false,
        readOnlyOnNew: false,
        useList: false,
        allowAdd: false,
        items: [],
        useLookup: false,
        lookupUrl: "",
        lookupKey: "",
        lookupLabels: null,
        lookupSearchs: null,
        lookupFormat1: "",
        lookupFormat2: "",
        showTitle: false,
        showHint: false,
        showDetail: false,
        fixTitle: false,
        fixDetail: false,
        section: "General",
        sectionWidth: "",
        row: 0,
        col: 0,
        labelField: "",
        decimal: 0,
        dateFormat: "DD-MMM-YYYY hh:mm:ss Z",
        unit: "",
        width: "",
        spaceBefore: 0,
        spaceAfter: 0,
      },
    },
  ];
  data.gridCfg = {
    fields: fields,
    setting: {
      idField: "_id",
      keywordFields: ["_id"],
      sortable: ["_id"],
    },
  };
  fetchRecord(props.journalID);
});
function fetchRecord(id) {
  axios
    .post(props.readUrl, {
      JournalType: props.journalType,
      JournalID: id,
    })
    .then((r) => {
      data.records = r.data.Approvals.filter((s) => {
        return s.Status == "REJECTED";
      });
      listControl.value.setRecords(data.records);
    })
    .catch((e) => console.log(e));
}
defineExpose({
  fetchRecord,
});
</script>
